import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavbarPage from "@/components/Navbar";
import FooterPage from "@/components/Footer";
import { ActivityProvider } from "@/context/ActivityContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Keen Keeper",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div>
          <ActivityProvider>
            <NavbarPage />
            {children}
            <FooterPage />
          </ActivityProvider>
        </div>
      </body>
    </html >
  );
}
